CREATE DATABASE ECOM;
USE ECOM;

CREATE TABLE USER(
	FULLNAME VARCHAR(30) PRIMARY KEY,
    EMAIL VARCHAR(30) NOT NULL,
    MOBILE VARCHAR(30),
    PASSWORD VARCHAR(30)
);

CREATE TABLE CART(
	CART_ID INT PRIMARY KEY auto_increment,
    FULLNAME VARCHAR(50) NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRODUCT_NAME VARCHAR(40) NOT NULL,
    PRODUCT_PRICE INT NOT NULL,
    QUANTITY INT NOT NULL DEFAULT 1,
    FOREIGN KEY (FULLNAME) REFERENCES USER(FULLNAME)
);

CREATE TABLE ORDERS(
	ORDER_ID INT PRIMARY KEY auto_increment,
    ORDER_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    FULLNAME VARCHAR(20) NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRODUCT_NAME VARCHAR(20) NOT NULL,
    PRODUCT_PRICE INT NOT NULL,
    QUANTITY INT NOT NULL
);

SELECT * FROM ORDERS;

INSERT INTO ORDERS (FULLNAME,PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE,QUANTITY)
 SELECT FULLNAME,PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE,QUANTITY FROM CART;